# prettier-ignore
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.backendsecretname}}
  namespace: {{.Values.backendnamespace}}
type: Opaque
data:
  .env: REFUQUJBU0VfVVJMPSJtb25nb2RiOi8vZGIuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9ieXRlYnJhaW5fZGIiCkpXVF9TRUNSRVQ9IkRlZXBha0AxMjM0Ig==
